// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import FormsController from "./forms_controller"
application.register("forms", FormsController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)
